name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      ganache:
        image: trufflesuite/ganache-cli
        ports:
          - 8545:8545

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - name: Install Truffle and Ganache

      run: npm install -g truffle 
    - name: install packages
      run: cd contract && npm install

    - name: Run Tests
      run: cd contract && truffle test --network ganache

  merge:

        needs: test
    
        runs-on: ubuntu-latest
    
        steps:
        
        - uses: actions/checkout@v2
        
        - name: Merge to main
          uses: devmasx/merge-branch@v1.4.0
          with:
            type: now
            label_name: 'auto-merged'
            target_branch: main